#!/usr/bin/env python3

from metasearcher import *

files = get_selected_files()

for file in files:
    attr_name = show_entry("Enter attribute name:")
    if attr_name is not None:
        metadata_file_path = get_metadata_file_path(file)
        metadata = load_metadata(metadata_file_path)
        if not attr_name in metadata:
            show_info(f"Attribute {attr_name} is not set.")
        else:
            attr_value = metadata[attr_name]
            show_info(f"Attribute {attr_name} has value {attr_value}")
