#!/usr/bin/env python3

from metasearcher import *

files = get_selected_files()

for file in files:
    attr_name = show_entry("Enter attribute name:")
    attr_value = show_entry("Enter attribute value:")
    if attr_name is not None and attr_value is not None:
        metadata_file_path = get_metadata_file_path(file)
        metadata = load_metadata(metadata_file_path)
        metadata[attr_name] = attr_value
        save_metadata(metadata, metadata_file_path)
