#!/usr/bin/env python3

from metasearcher import *

files = get_selected_files()

for file in files:
    # find old rating
    metadata_file_path = get_metadata_file_path(file)
    metadata = load_metadata(metadata_file_path)
    val_init = 50
    if "rating" in metadata:
        val_init = metadata["rating"]

    # find new rating
    new_rating = show_gui_set_rating(val_init=val_init)

    # save new rating
    if new_rating is not None:
        metadata["rating"] = new_rating
        save_metadata(metadata, metadata_file_path)
