#!/usr/bin/env python3


from metasearcher import *
import subprocess


def show_gui_attributes(attributes: dict) -> None:
    cmd = [
        "zenity",
        "--list",
        "--title", "File attributes",
        "--text", "File has these attributes:",
        "--column", "Name",
        "--column", "Value"
    ]

    for name, value in attributes.items():
        cmd.append(name)
        cmd.append(value.__str__())

    completed_process = subprocess.run(cmd, capture_output=True)
    returncode = completed_process.returncode
    stdout = completed_process.stdout.decode("utf8").strip()
    return returncode, stdout

files = get_selected_files()

for file in files:
    metadata_file_path = get_metadata_file_path(file)
    metadata = load_metadata(metadata_file_path)
    show_gui_attributes(metadata)
